#ifndef GDAL_GO_GDAL_PREAMBLE_H
#define GDAL_GO_GDAL_PREAMBLE_H

#include "gdal.h"

static const char* _GDALMD_AREA_OR_POINT(void) { return GDALMD_AREA_OR_POINT; }
static const char* _GDALMD_AOP_AREA(void)      { return GDALMD_AOP_AREA; }
static const char* _GDALMD_AOP_POINT(void)     { return GDALMD_AOP_POINT; }

static const char* _GDAL_DS_LAYER_CREATIONOPTIONLIST(void) { return GDAL_DS_LAYER_CREATIONOPTIONLIST; }

static const char* _GDAL_DMD_LONGNAME(void)                                       { return GDAL_DMD_LONGNAME; }
static const char* _GDAL_DMD_HELPTOPIC(void)                                      { return GDAL_DMD_HELPTOPIC; }
static const char* _GDAL_DMD_MIMETYPE(void)                                       { return GDAL_DMD_MIMETYPE; }
static const char* _GDAL_DMD_EXTENSION(void)                                      { return GDAL_DMD_EXTENSION; }
static const char* _GDAL_DMD_CONNECTION_PREFIX(void)                              { return GDAL_DMD_CONNECTION_PREFIX; }
static const char* _GDAL_DMD_EXTENSIONS(void)                                     { return GDAL_DMD_EXTENSIONS; }
static const char* _GDAL_DMD_CREATIONOPTIONLIST(void)                             { return GDAL_DMD_CREATIONOPTIONLIST; }
static const char* _GDAL_DMD_OVERVIEW_CREATIONOPTIONLIST(void)                    { return GDAL_DMD_OVERVIEW_CREATIONOPTIONLIST; }
static const char* _GDAL_DMD_MULTIDIM_DATASET_CREATIONOPTIONLIST(void)            { return GDAL_DMD_MULTIDIM_DATASET_CREATIONOPTIONLIST; }
static const char* _GDAL_DMD_MULTIDIM_GROUP_CREATIONOPTIONLIST(void)              { return GDAL_DMD_MULTIDIM_GROUP_CREATIONOPTIONLIST; }
static const char* _GDAL_DMD_MULTIDIM_DIMENSION_CREATIONOPTIONLIST(void)          { return GDAL_DMD_MULTIDIM_DIMENSION_CREATIONOPTIONLIST; }
static const char* _GDAL_DMD_MULTIDIM_ARRAY_CREATIONOPTIONLIST(void)              { return GDAL_DMD_MULTIDIM_ARRAY_CREATIONOPTIONLIST; }
static const char* _GDAL_DMD_MULTIDIM_ARRAY_OPENOPTIONLIST(void)                  { return GDAL_DMD_MULTIDIM_ARRAY_OPENOPTIONLIST; }
static const char* _GDAL_DMD_MULTIDIM_ATTRIBUTE_CREATIONOPTIONLIST(void)          { return GDAL_DMD_MULTIDIM_ATTRIBUTE_CREATIONOPTIONLIST; }
static const char* _GDAL_DMD_OPENOPTIONLIST(void)                                 { return GDAL_DMD_OPENOPTIONLIST; }
static const char* _GDAL_DMD_CREATIONDATATYPES(void)                              { return GDAL_DMD_CREATIONDATATYPES; }
static const char* _GDAL_DMD_CREATIONFIELDDATATYPES(void)                         { return GDAL_DMD_CREATIONFIELDDATATYPES; }
static const char* _GDAL_DMD_CREATIONFIELDDATASUBTYPES(void)                      { return GDAL_DMD_CREATIONFIELDDATASUBTYPES; }
static const char* _GDAL_DMD_MAX_STRING_LENGTH(void)                              { return GDAL_DMD_MAX_STRING_LENGTH; }
static const char* _GDAL_DMD_CREATION_FIELD_DEFN_FLAGS(void)                      { return GDAL_DMD_CREATION_FIELD_DEFN_FLAGS; }
static const char* _GDAL_DMD_SUBDATASETS(void)                                    { return GDAL_DMD_SUBDATASETS; }
static const char* _GDAL_DCAP_CREATE_SUBDATASETS(void)                            { return GDAL_DCAP_CREATE_SUBDATASETS; }
static const char* _GDAL_DMD_NUMERIC_FIELD_WIDTH_INCLUDES_DECIMAL_SEPARATOR(void) { return GDAL_DMD_NUMERIC_FIELD_WIDTH_INCLUDES_DECIMAL_SEPARATOR; }
static const char* _GDAL_DMD_NUMERIC_FIELD_WIDTH_INCLUDES_SIGN(void)              { return GDAL_DMD_NUMERIC_FIELD_WIDTH_INCLUDES_SIGN; }
static const char* _GDAL_DCAP_OPEN(void)                                          { return GDAL_DCAP_OPEN; }
static const char* _GDAL_DCAP_CREATE(void)                                        { return GDAL_DCAP_CREATE; }
static const char* _GDAL_DCAP_CREATE_MULTIDIMENSIONAL(void)                       { return GDAL_DCAP_CREATE_MULTIDIMENSIONAL; }
static const char* _GDAL_DCAP_CREATECOPY(void)                                    { return GDAL_DCAP_CREATECOPY; }
static const char* _GDAL_DCAP_CREATE_ONLY_VISIBLE_AT_CLOSE_TIME(void)             { return GDAL_DCAP_CREATE_ONLY_VISIBLE_AT_CLOSE_TIME; }
static const char* _GDAL_DCAP_VECTOR_TRANSLATE_FROM(void)                         { return GDAL_DCAP_VECTOR_TRANSLATE_FROM; }
static const char* _GDAL_DCAP_CREATECOPY_MULTIDIMENSIONAL(void)                   { return GDAL_DCAP_CREATECOPY_MULTIDIMENSIONAL; }
static const char* _GDAL_DCAP_MULTIDIM_RASTER(void)                               { return GDAL_DCAP_MULTIDIM_RASTER; }
static const char* _GDAL_DCAP_SUBCREATECOPY(void)                                 { return GDAL_DCAP_SUBCREATECOPY; }
static const char* _GDAL_DCAP_APPEND(void)                                        { return GDAL_DCAP_APPEND; }
static const char* _GDAL_DCAP_UPDATE(void)                                        { return GDAL_DCAP_UPDATE; }
static const char* _GDAL_DCAP_VIRTUALIO(void)                                     { return GDAL_DCAP_VIRTUALIO; }
static const char* _GDAL_DCAP_RASTER(void)                                        { return GDAL_DCAP_RASTER; }
static const char* _GDAL_DCAP_VECTOR(void)                                        { return GDAL_DCAP_VECTOR; }
static const char* _GDAL_DCAP_GNM(void)                                           { return GDAL_DCAP_GNM; }
static const char* _GDAL_DCAP_CREATE_LAYER(void)                                  { return GDAL_DCAP_CREATE_LAYER; }
static const char* _GDAL_DCAP_DELETE_LAYER(void)                                  { return GDAL_DCAP_DELETE_LAYER; }
static const char* _GDAL_DCAP_CREATE_FIELD(void)                                  { return GDAL_DCAP_CREATE_FIELD; }
static const char* _GDAL_DCAP_DELETE_FIELD(void)                                  { return GDAL_DCAP_DELETE_FIELD; }
static const char* _GDAL_DCAP_REORDER_FIELDS(void)                                { return GDAL_DCAP_REORDER_FIELDS; }
static const char* _GDAL_DMD_ALTER_FIELD_DEFN_FLAGS(void)                         { return GDAL_DMD_ALTER_FIELD_DEFN_FLAGS; }
static const char* _GDAL_DMD_ILLEGAL_FIELD_NAMES(void)                            { return GDAL_DMD_ILLEGAL_FIELD_NAMES; }
static const char* _GDAL_DCAP_NOTNULL_FIELDS(void)                                { return GDAL_DCAP_NOTNULL_FIELDS; }
static const char* _GDAL_DCAP_UNIQUE_FIELDS(void)                                 { return GDAL_DCAP_UNIQUE_FIELDS; }
static const char* _GDAL_DCAP_DEFAULT_FIELDS(void)                                { return GDAL_DCAP_DEFAULT_FIELDS; }
static const char* _GDAL_DCAP_NOTNULL_GEOMFIELDS(void)                            { return GDAL_DCAP_NOTNULL_GEOMFIELDS; }
static const char* _GDAL_DCAP_NONSPATIAL(void)                                    { return GDAL_DCAP_NONSPATIAL; }
static const char* _GDAL_DCAP_CURVE_GEOMETRIES(void)                              { return GDAL_DCAP_CURVE_GEOMETRIES; }
static const char* _GDAL_DCAP_MEASURED_GEOMETRIES(void)                           { return GDAL_DCAP_MEASURED_GEOMETRIES; }
static const char* _GDAL_DCAP_Z_GEOMETRIES(void)                                  { return GDAL_DCAP_Z_GEOMETRIES; }
static const char* _GDAL_DMD_GEOMETRY_FLAGS(void)                                 { return GDAL_DMD_GEOMETRY_FLAGS; }
static const char* _GDAL_DCAP_FEATURE_STYLES(void)                                { return GDAL_DCAP_FEATURE_STYLES; }
static const char* _GDAL_DCAP_FEATURE_STYLES_READ(void)                           { return GDAL_DCAP_FEATURE_STYLES_READ; }
static const char* _GDAL_DCAP_FEATURE_STYLES_WRITE(void)                          { return GDAL_DCAP_FEATURE_STYLES_WRITE; }
static const char* _GDAL_DCAP_COORDINATE_EPOCH(void)                              { return GDAL_DCAP_COORDINATE_EPOCH; }
static const char* _GDAL_DCAP_MULTIPLE_VECTOR_LAYERS(void)                        { return GDAL_DCAP_MULTIPLE_VECTOR_LAYERS; }
static const char* _GDAL_DCAP_FIELD_DOMAINS(void)                                 { return GDAL_DCAP_FIELD_DOMAINS; }
static const char* _GDAL_DCAP_RELATIONSHIPS(void)                                 { return GDAL_DCAP_RELATIONSHIPS; }
static const char* _GDAL_DCAP_CREATE_RELATIONSHIP(void)                           { return GDAL_DCAP_CREATE_RELATIONSHIP; }
static const char* _GDAL_DCAP_DELETE_RELATIONSHIP(void)                           { return GDAL_DCAP_DELETE_RELATIONSHIP; }
static const char* _GDAL_DCAP_UPDATE_RELATIONSHIP(void)                           { return GDAL_DCAP_UPDATE_RELATIONSHIP; }
static const char* _GDAL_DCAP_FLUSHCACHE_CONSISTENT_STATE(void)                   { return GDAL_DCAP_FLUSHCACHE_CONSISTENT_STATE; }
static const char* _GDAL_DCAP_HONOR_GEOM_COORDINATE_PRECISION(void)               { return GDAL_DCAP_HONOR_GEOM_COORDINATE_PRECISION; }
static const char* _GDAL_DCAP_UPSERT(void)                                        { return GDAL_DCAP_UPSERT; }
static const char* _GDAL_DMD_RELATIONSHIP_FLAGS(void)                             { return GDAL_DMD_RELATIONSHIP_FLAGS; }
static const char* _GDAL_DMD_RELATIONSHIP_RELATED_TABLE_TYPES(void)               { return GDAL_DMD_RELATIONSHIP_RELATED_TABLE_TYPES; }
static const char* _GDAL_DCAP_RENAME_LAYERS(void)                                 { return GDAL_DCAP_RENAME_LAYERS; }
static const char* _GDAL_DMD_CREATION_FIELD_DOMAIN_TYPES(void)                    { return GDAL_DMD_CREATION_FIELD_DOMAIN_TYPES; }
static const char* _GDAL_DMD_ALTER_GEOM_FIELD_DEFN_FLAGS(void)                    { return GDAL_DMD_ALTER_GEOM_FIELD_DEFN_FLAGS; }
static const char* _GDAL_DMD_SUPPORTED_SQL_DIALECTS(void)                         { return GDAL_DMD_SUPPORTED_SQL_DIALECTS; }
static const char* _GDAL_DMD_PLUGIN_INSTALLATION_MESSAGE(void)                    { return GDAL_DMD_PLUGIN_INSTALLATION_MESSAGE; }
static const char* _GDAL_DMD_UPDATE_ITEMS(void)                                   { return GDAL_DMD_UPDATE_ITEMS; }
static const char* _GDAL_DIM_TYPE_HORIZONTAL_X(void)                              { return GDAL_DIM_TYPE_HORIZONTAL_X; }
static const char* _GDAL_DIM_TYPE_HORIZONTAL_Y(void)                              { return GDAL_DIM_TYPE_HORIZONTAL_Y; }
static const char* _GDAL_DIM_TYPE_VERTICAL(void)                                  { return GDAL_DIM_TYPE_VERTICAL; }
static const char* _GDAL_DIM_TYPE_TEMPORAL(void)                                  { return GDAL_DIM_TYPE_TEMPORAL; }
static const char* _GDAL_DIM_TYPE_PARAMETRIC(void)                                { return GDAL_DIM_TYPE_PARAMETRIC; }
static const char* _GDAL_DCAP_REOPEN_AFTER_WRITE_REQUIRED(void)                   { return GDAL_DCAP_REOPEN_AFTER_WRITE_REQUIRED; }
static const char* _GDAL_DCAP_CAN_READ_AFTER_DELETE(void)                         { return GDAL_DCAP_CAN_READ_AFTER_DELETE; }
static const char* _GDsCAddRelationship(void)                                     { return GDsCAddRelationship; }
static const char* _GDsCDeleteRelationship(void)                                  { return GDsCDeleteRelationship; }
static const char* _GDsCUpdateRelationship(void)                                  { return GDsCUpdateRelationship; }
static const char* _GDsCFastGetExtent(void)                                       { return GDsCFastGetExtent; }
static const char* _GDsCFastGetExtentWGS84LongLat(void)                           { return GDsCFastGetExtentWGS84LongLat; }

#endif /* GDAL_GO_GDAL_PREAMBLE_H */
